# ------------------------------------------------
#				AntiCheat
# ------------------------------------------------
# ------------------------------------------------
# Main
# ------------------------------------------------
Ban:
  Command: "ban %player%"